apiVersion: apps/v1
kind: Deployment
metadata:
  name: easydoor-api-dp
  namespace: easydoor-api
  labels:
    app: easydoor-api
spec:
  selector:
    matchLabels:
      app: easydoor-api
  template:
    metadata:
      labels:
        app: easydoor-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: easydoor-api
          image: ghcr.io/gabezy/easydoor-api:sha-8b11b75
          imagePullPolicy: IfNotPresent

          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: easydoor-api-secrets
                  key: POSTGRES_HOST

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: easydoor-api-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easydoor-api-secrets
                  key: POSTGRES_PASSWORD

          ports:
            - name: http
              containerPort: 8080

          startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
            failureThreshold: 30
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            periodSeconds: 25
            failureThreshold: 3
            timeoutSeconds: 5