apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: easydoor-api

resources:
  - namespace.yaml
  - deployment.yaml
  - svc.yaml

images:
  - name: ghcr.io/gabezy/easydoor-api
    newName: ghcr.io/gabezy/easydoor-api
    newTag: sha-initial