quarkus:
  application:
    name: easydoorapi
    version: 1.0.0-SNAPSHOT
  swagger-ui:
    always-include: true

  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://db.docker.orb.local/easydoor

  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false

  flyway:
    username: postgres
    password: postgres

  http:
    port: 8080
    cors: true

  log:
    level: INFO
    category:
      "br.com.gabezy.easydoorapi": DEBUG

jwt:
  access-token:
    ttl-seconds: 900
  refresh-token:
    ttl-seconds: 604800
server:
  shutdown:
    delay-seconds: 5
mp:
  jwt:
    verify:
      publickey:
        location: "/jwt/publicKey.pem"
      issuer: "easydoor-api"

smallrye:
  jwt:
    sign:
      key:
        location: "/jwt/privateKey.pem"